### PR TITLE
Psi4: latest version changes header line

### PR DESCRIPTION
**Pull request by berquist**

### CODE REVIEW

**Comment by langner** [comment]
Can you run the unit test for this regression file?

**Comment by berquist** [comment]
I'll remove this file and re-run with the current test suite SP input, so that I don't have to rewrite the entire unit test in `regression.py`.

**Comment by langner** [comment]
There is code in regression.py that allows you to automatically create a regression test from existing unit tests.

**Comment by langner** [comment]
> Is it sufficient to just add these lines to create the regression test(s)? I got the parsed and tested output, so I'm assuming yes.

So it seems! Could we also keep the output file with thiocarbamic acid?

**Pull request merged**
