### PR TITLE
 Added Turbomole example with raman.out

### PR DESCRIPTION
**Pull request by dkratzert**

### CODE REVIEW

**Comment by langner** [comment]
Thanks Daniel - is there something about this example that makes it a good regression?

**Comment by langner** [comment]
I'm not sure if we parse these files correctly, but they don't crash the parse so we can merge them in as a regression.

**Comment by berquist** [comment]
I think they are crashing things, https://github.com/cclib/cclib/pull/780 needed to go in first.

**Comment by langner** [comment]
Reverting...

**Pull request merged**
