### PR TITLE
Adds Orca CASSCF optimization regression.

### PR DESCRIPTION
**Pull request by jevandezande**
Orca logfile performing an optimization on H2-.
This tests both the open shell parsing and the parsing of optimizations.

### CODE REVIEW

**Comment by berquist** [comment]
Can you fix the conflict? The entire old Psi section should be replaced with the new distinct Psi3 + Psi4 section; only your line is different.

**Comment by langner** [comment]
Jonathon, I sent a PR for the conflict: jevandezande/cclib-data#1. Once that's in, you should be able to submit this soon after.

**Comment by berquist** [comment]
Why are so many things now changed in the diff?

**Comment by jevandezande** [comment]
I merged in a PR from @langner. I'm not sure why it added a bunch of new files. Perhaps I merged it wrong (I'd never used the web interface before)?

**Comment by berquist** [comment]
No, I don't think so. It would probably waste time for us to diagnose this rather than making a new PR. I'll look at it as soon as you post it.

**Comment by langner** [comment]
Hm, yeah, it could've been me that messed something up. Are you OK with creating a new PR?

**Pull request closed without merging**
