### PR TITLE
Orca steom

### PR DESCRIPTION
**Pull request by oliver-s-lee**
Added a regression file for unusual orbital singly excited contributions with forms like:
`  -0.103557    42 -> x    42 -> 102`

### CODE REVIEW

**Review by berquist — CHANGES_REQUESTED** [review]
1. Once the conflict is fixed, is the ORCA file good to go in?
2. Can you separate out this other Gaussian output and also give the file a more descriptive name?

**Comment by berquist** [comment]
Is this what you expect?
```console
Attempting to read ORCA/ORCA5.0/steom_orbs.log
[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Attribute etenergies changed value ([33836.9, 36610.5] -> [58430.9, 68624.7, 76876.5, 74256.2, 75911.9, 79565.9, 76654.9, 98867.4, 445807.6])
[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Attribute etenergies changed value ([58430.9, 68624.7, 76876.5, 74256.2, 75911.9, 79565.9, 76654.9, 98867.4, 445807.6] -> [-3863.3, 5105.2, 6175.2,
 8684.6, 13523.6, 15104.0, 17891.2, 51559.7])
[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Attribute etsyms changed value (['Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet'] -> ['Singlet',
'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet'])
[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Warning:: the state may have not converged with respect to active space

[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Warning:: the state may have not converged with respect to active space

[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Attribute etenergies changed value ([-3863.3, 5105.2, 6175.2, 8684.6, 13523.6, 15104.0, 17891.2, 51559.7] -> [22054.5, 23776.0])
[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Attribute etsyms changed value (['Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet', 'Singlet'] -> ['Triplet', 'Triplet'])
[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Overwriting previous multipole moments with new values
[ORCA ORCA/ORCA5.0/steom_orbs.log WARNING] Attribute moments changed value ([array([-8.4234e-02,  1.0000e-06, -1.0000e-06]), array([ 5.71618393e+00,  5.08349246e-05, -0.00000000e+00])] -> [a
rray([-8.4234e-02,  1.0000e-06, -1.0000e-06]), array([4.58032838, 0.00922654, 0.01779222])])
cclib can parse the following attributes from ORCA/ORCA5.0/steom_orbs.log:
  atomcharges
  atomcoords
  atommasses
  atomnos
  ccenergies
  charge
  coreelectrons
  etenergies
  etsecs
  etsyms
  homos
  metadata
  moenergies
  moments
  mosyms
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
```

**Comment by oliver-s-lee** [comment]
In a nutshell, yes. Before the PR that fixed this the log file would have thrown an exception about casting str to int or whatever python says.

The warnings are a separate issue I think. For STEOM, we parse each of the excited state calcs in turn and replace any old data with the next (which will be a higher level of theory) until we get to the final STEOM energies. Works fine, but leads to lots of 'Attribute changed' warnings as we discard old data. Perhaps worth fixing with `check_change` of `set_attribute`?

**Review by berquist — APPROVED** [review]

**Comment by berquist** [comment]
I forgot about `check_change`.  Yes, and I feel like we could use some logging for what is actually being parsed...for example, for the longest time in ORCA when reading a CCSD(T) calculation you'd only get the CCSD result since (T) wasn't parsed.  If you saw at `INFO` or `DEBUG` level "parsed CCSD", "parsed CCSD(T)", "parsed EOM-CCSD" etc. maybe it would be useful.

**Comment by oliver-s-lee** [comment]
@berquist yeah me too, I just had a feeling that these warnings could be hidden somehow.

Section logging is an interesting idea, although for the specific problem you describe this should definitely also be covered in metadata somehow. Maybe this sort of logging would be a good fit for the changes in V2? Speaking of, is there a breakdown of the plan moving forward somewhere? I see there's some cool stuff planned in eg https://github.com/cclib/cclib/pull/1325 but not sure of the long-term direction.

**Pull request merged**
