### PR TITLE
regression.py: GAMESS-UK8.0/dvb_ir.out atomcoords

### PR DESCRIPTION
**Pull request by mwykes**
Added regression test to check if parsed atomcoords are converted from bohr to ang in GAMESS-UK8.0/dvb_ir.out, as requested in the discussion of pull request #17. This test will fail until cclib pull request #226 is merged.

### CODE REVIEW

**Comment by langner** [comment]
Is that the same file as we have in the unit tests?

**Comment by mwykes** [comment]
Yes, it is the same file as we have in the unit tests.

**Comment by langner** [comment]
> Yes, it is the same file as we have in the unit tests.

Ah. In that case, we can just add an additional test

**Comment by mwykes** [comment]
By adding an additional test, do you mean testing the geometry of that file
in the cclib unit tests ? I think that is pretty much what I had in an
earlier pull request - though I did it in the generic freq unit test (thus
testing geometries for dvb_ir.out for all parsers). Or would you want to
see a the unit test only run for GAMESSUK ?

**Comment by langner** [comment]
> By adding an additional test, do you mean testing the geometry of that file
> in the cclib unit tests ? I think that is pretty much what I had in an
> earlier pull request - though I did it in the generic freq unit test (thus
> testing geometries for dvb_ir.out for all parsers). Or would you want to
> see a the unit test only run for GAMESSUK ?

I would add it as a standard test to the IR unit tests for all parsers (should pass anyway, right?). If that proves problematic, you can add it to just the one parser - add a comment explaining things.

Sorry for the confusion!

**Comment by mwykes** [comment]
OK sure, I'll do that. This is exactly what I had done in an earlier pull
request, and it works fine. What I did previously was to copy the
testatomcoords method of GenericGeoOptTest into GenericIRTest, leading to
the same code being in two places, which is perhaps not the best solution.
You wrote in another thread that your attitude to redundant tests is
changing, and so you now think the more tests the better. In this case, it
might be worth refactoring the unit test classes to define each test method
within its own class inside in a dedicated testmethods.py. This would allow
the test methods which are currently in different test classes to be easily
imported and used in multiple places (e.g.  testatomcoords could be used in
both GenericGeoOptTest and GenericIRTest), without code duplication. Please
let me know what you think about this idea, and whether or not it makes
sense to do it that way.

**Comment by berquist** [comment]
At this point, is this something that can be closed and not merged? Rewriting things so that `testatomcoords` could be used in both `GenericGeoOptTest` and `GenericIRTest` would necessitate a separate issue/PR.

**Comment by langner** [comment]
> At this point, is this something that can be closed and not merged? Rewriting things so that testatomcoords could be used in both GenericGeoOptTest and GenericIRTest would necessitate a separate issue/PR.

OK, let's open up an issue for that in that case and then close this for now.

**Comment by langner** [comment]
Create issue for re-organizing tests in cclib/cclib#602.

**Pull request closed without merging**
