### PR TITLE
Added ethane MP5 regression file that triggers #1163

### PR DESCRIPTION
**Pull request by oliver-s-lee**

### CODE REVIEW

**Comment by shivupa** [comment]
Can you add this to `regressionfiles.txt`

**Comment by berquist** [comment]
I'm getting
```
$ ccget --list data/regression/Gaussian/Gaussian16/Ethane.mp5.log                                           
Attempting to read data/regression/Gaussian/Gaussian16/Ethane.mp5.log
[Gaussian data/regression/Gaussian/Gaussian16/Ethane.mp5.log ERROR] Encountered error when parsing.
[Gaussian data/regression/Gaussian/Gaussian16/Ethane.mp5.log ERROR] Last line read:  Ethane_Single_Point_Singlet_MP5_Gas_Phase_6_31G_

Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/miniforge3-4.10.3-10/envs/cclib_310/bin/ccget", line 33, in <module>
    sys.exit(load_entry_point('cclib', 'console_scripts', 'ccget')())
  File "/home/eric/development/forks/python/cclib_pr_review/cclib/scripts/ccget.py", line 178, in ccget
    data = ccread(filename, **kwargs)
  File "/home/eric/development/forks/python/cclib_pr_review/cclib/io/ccio.py", line 170, in ccread
    return log.parse()
  File "/home/eric/development/forks/python/cclib_pr_review/cclib/parser/logfileparser.py", line 321, in parse
    self.extract(inputfile, line)
  File "/home/eric/development/forks/python/cclib_pr_review/cclib/parser/gaussianparser.py", line 932, in extract
    mp5energy = utils.float(line.split("=")[2])
IndexError: list index out of range
```
which corresponds to line 101 in the file.

**Comment by berquist** [comment]
Ah, I can't read, I saw https://github.com/cclib/cclib/issues/1163 was closed and thought it referred to a PR. https://github.com/cclib/cclib/pull/1164 is the actual PR.

**Comment by berquist** [comment]
I've checked that https://github.com/cclib/cclib/pull/1164 does fix this, so this PR needs to go in after the main one.

**Pull request merged**
