### PR TITLE
Add Gaussian 09 output files for PES scan and anharmonic vibrations

### PR DESCRIPTION
**Pull request by Schamnad**
Gaussian files provided by Dr. Geoff Hutchison to test scan and anharmonic vibration attributes.

### CODE REVIEW

**Comment by berquist** [comment]
These seem to parse fine already. The files in the regression suite are for calculations that either caused errors during parsing, parse some attributes and not others, or generally cause some incorrect or unexpected behavior. If there aren't any issues with these files, I'm not sure it makes sense to add them.

**Comment by Schamnad** [comment]
Apologies for not giving more context in the PR. These files are required because regression tests for 5 attributes i.e. scancoords, scanenergies, scannames, scanparm, vibanharms haven't been written. None of the files in the present repository have these attribute values. This has been noted down in the cclib docs as well - [Link](https://cclib.github.io/data_dev.html#details-of-current-implementation)

Presently the [testScan.py](https://github.com/cclib/cclib/blob/master/test/data/testScan.py) file doesn't have the required tests for these attributes

**Comment by berquist** [comment]
I agree with @ATenderholt that it would be better for the standard test suite to be extended, since enough programs can run these types of calculations.

I only have access to DALTON, GAMESS-US, Molpro, NWChem, ORCA, Psi4, and Q-Chem. It might be best to take these two files as the "default" test examples and base calculations using other programs on the structures/methods/basis sets used here.

**Comment by langner** [comment]
I concur.

**Comment by berquist** [comment]
Ok. @Schamnad, if you make a pull request with these files added to https://github.com/cclib/cclib/tree/master/data/Gaussian/basicGaussian09, then we can start writing the standard tests. Then I'll close this.

You should also ask @ghutchis to send you the formatted checkpoint files (*.fchk) as well.

**Comment by Schamnad** [comment]
Will create a PR once I receive the checkpoint files from @ghutchis

**Comment by ghutchis** [comment]
[ch3oh-freq.fchk.gz](https://github.com/cclib/cclib-data/files/314648/ch3oh-freq.fchk.gz)
[water-pes.fchk.gz](https://github.com/cclib/cclib-data/files/314649/water-pes.fchk.gz)

**Comment by Schamnad** [comment]
@ghutchis thank you for the checkpoint files. Have created a [PR](https://github.com/cclib/cclib/pull/281) in the cclib repository.

**Comment by langner** [comment]
This was dealt with over in the main repo.

**Pull request closed without merging**
